### ISSUE TITLE
How to get status code from an error response?

### ISSUE THREAD

**Issue by slavkomae** [Microsoft/typed-rest-client#14]
hi -- I'm using the create method to post an object to an external REST api. The response returned can have various status codes (even 300+) that indicate various things -- most of which are not actually errors. However, anything that returns with code not 2xx gets handled in the promise's catch block where the promise is rejected -- and the object I get back has properties "message" and "stack", but no status code (or anything else). Since I do need the status code, not just the message -- how do I get it? Thanks in advance.

UPDATE: Looking at the code it seems that you're swallowing this: https://github.com/Microsoft/typed-rest-client/blob/3587b31fe5b77f2d57b3ac5fb0f722fb1485ea6e/lib/RestClient.ts#L210-L220

Is there really no way to get the exact status code of a non-2xx response??? I find that hard to fathom.

In addition, what if one needs other info from a non-2xx response, like its data?

**Comment by bryanmacfarlane** [comment]
I will fix this.  Thanks for the suggestion.

On a related note, there is a question whether some non error codes should even throw.  Note that we also just added 3xx redirect supports so that's out of the mix.

Thoughts?

**Comment by bryanmacfarlane** [comment]
Looking at this now.  Note the http client doesn't throw it's pure request / response in all cases.  It's the higher level rest client that does the http request and turns that into a restful object.  So, for example, a 404 will return an object.  As noted above, we recently added 302 support.

What I'm considering:
- Only a 500 throws an exception.  Even in that case, I will add the status code and body to the error object.
- 3xx redirects are handled by default.
- 4xx would return response (not throw) but object / result would be null

Thoughts?

**Comment by peterblazejewicz** [comment]
Bryan, this could be alreayd late to do this, but can the api be aligned to e.g. Fetch API specs in this details?
https://fetch.spec.whatwg.org/#fetch-method
https://github.github.io/fetch/ (polyfill for fetch specs)
Chrome impl for redirects: https://www.chromestatus.com/feature/4614142321229824

**Comment by bryanmacfarlane** [comment]
Thanks for all the feedback.  We met and here's where we landed.

This ships an http and rest client.  

The http client is a lower level http client.  It does not throw unless something truly exceptional happened.  Even a 500 successfully returns with the promise resolved.  

The rest client is a higher level resource client.  200s will be resolved and 3xx redirects will be handled for you by default.  In order to write linear code with the higher level client without checking after every call, the higher level rest client will throw on 4xx+ (3xx redirs handled for you). 

But, to address the root concern here, I will make sure the error object return code and the message.

**Comment by bryanmacfarlane** [comment]
Fixed. Details here:

https://github.com/Microsoft/typed-rest-client#errors

and

https://github.com/Microsoft/typed-rest-client/blob/master/test/resttests.ts#L38

**Comment by bryanmacfarlane** [comment]
typed-rest-client@0.14.2 has the fix
