### ISSUE TITLE
Rest client not minifying request body

### ISSUE THREAD

**Issue by blackbaud-brandonhare** [microsoft/typed-rest-client#198]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/typed-rest-client/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/typed-rest-client/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 12.14.1
Npm version: 6.13.4
OS and version: Mojave 10.14.6
typed-rest-client version: 1.7.1

### Issue Description
When making a request with a request body through the rest client, it stringifies the body with white space. This makes the request body unnecessarily large.
https://github.com/microsoft/typed-rest-client/blob/master/lib/RestClient.ts#L110

### Expected behaviour
It should stringify without space included.

### Actual behaviour
It stringifies the request with a space of 2.

### Steps to reproduce
1. Make any request with the rest client that accepts a request body.
2. Verify the request body includes white space.
3. 
4. 
5.

**Comment by andrecadete** [comment]
Not sure why this was closed back in 2020.. 

Appart from the original complaint which is related to peformance/unnecessary byte usage, there's a much worse consequence: this forces us to comply with the HTTP client's choice of spaces in order to use the standard HTTP Header Signature auth.

It should either use no spaces or at the very least allow this to be configured..

This is where the issue happens for the `create<T>()` method, same issue exists in other methods though:
https://github.com/microsoft/typed-rest-client/blob/7ad2a7a001e5fd78c08e466908ed63225a892db9/lib/RestClient.ts#L110
