### ISSUE TITLE
Confusing deprecation: "1.8.5 contains changes that are not compatible with Node 6"

### ISSUE THREAD

**Issue by nicojs** [microsoft/typed-rest-client#294]
The current latest release of `typed-rest-client` is v1.8.5, but when you navigate to the [package on NPM](https://www.npmjs.com/package/typed-rest-client) it states this message:

![image](https://user-images.githubusercontent.com/1828233/131315253-e7470b5d-a08d-44bf-9a9e-53f8e56f55d8.png)

What does this mean? Node 6 has been [end of life for about half a decade](https://nodejs.org/en/about/releases/). Should I be worried when I use node 12? 

Further more, if it is a problem, what should I do? I've found #291 which states that migrating back to 1.8.4 solves a problem for them. Does that mean that migrating to 1.8.4 solves it? If so, could that be stated in the deprecation message?

We're using typed-rest-client in [stryker.js](https://stryker-mutator.io). Currently every user that installs Stryker sees this message:

> npm WARN deprecated typed-rest-client@1.8.5: 1.8.5 contains changes that are not compatible with Node 6

**Comment by EzzhevNikita** [comment]
Hi @nicojs, typed-rest-client contains changes related to the processing of NO_PROXY env variable (related [PR](https://github.com/microsoft/typed-rest-client/pull/286)) that happens with using a regular expression with the construction that is not supported in Node 6. Since this library is used by in-the-box tasks and some of them still use Node 6 we need to keep the support of this Node version. For newer versions of Node 1.8.5 there are no known issues with backward compatibility. In any way, I recommend using 1.8.4 version of typed-rest-client to get rid of this warning.

**Comment by EzzhevNikita** [comment]
@nicojs UPD: we've published typed-rest-client@1.8.6 which contains revert the changes made in 1.8.5, so, you could just use the latest version of the package and there shouldn't be a warning message.

**Comment by nicojs** [comment]
Ah thanks @EzzhevNikita. I was hoping for a solution like that. Great work. 👍
