### ISSUE TITLE
Difference between this and RESTyped?

### ISSUE THREAD

**Issue by rawrmaan** [Microsoft/typed-rest-client#48]
Hey there, so I noticed that this project and my project RESTyped (https://github.com/rawrmaan/restyped) launched at similar times. I'm trying to understand the exact goals of this project and if it might be worthwhile to combine our efforts here.

Any thoughts? Thanks!

**Comment by bryanmacfarlane** [comment]
This actually started in 2015 as part of the vso node agent (written in node and typescript), which broke out into [vso-node-api](https://github.com/Microsoft/vsts-node-api) and then because we wanted to use in VS Code plugins in VSTS and many vsts task authors were using it outside of the node api (other http calls) we broke it out to keep our tasks light and layered.

It focused on some of the enterprise aspects which most libraries might not focus on because it's used client side in VS Code and our build tasks.  Specifically support for client side certificates, ntlm authentication, proxy etc...  This also has a layered approach offering an http client with the same features.

We welcome contributions but note that one of the key features is we want to stay very lightweight and pretty core.  We don't declare the rest services - the vsts node api is generated off of our vsts services.

Hope that answers your questions.

**Comment by rawrmaan** [comment]
Got it. Sounds like our projects are going in pretty different directions. Thanks Bryan!

**Comment by bryanmacfarlane** [comment]
No problem.  Best of luck!
