### ISSUE TITLE
index.d.ts is empty

### ISSUE THREAD

**Issue by leon** [Microsoft/typed-rest-client#59]
I've installed typed-rest-client via yarn and npm.

The typings for the 1.0.7 release are empty. which causes intellij to freak out.

Did the last deploy not go well?

https://unpkg.com/typed-rest-client@1.0.7/Index.d.ts

**Comment by leon** [comment]
Sorry my bad. it "is" empty.
Should have looked twice.

**Comment by bryanmacfarlane** [comment]
Hey, just following up to ensure there's not actually as issue using this in intellij.  The real definitions are in RestClient.d.ts and HttpClient.d.ts.  We could probably eliminate the need the Index.ts since it used to be a way to aggregate old deprecated typings (which are obsoleted now with npm support).  Now it's just an odd file.
